### ISSUE TITLE
Add a Navbar on left side of each page

### ISSUE THREAD

**Issue by orhan-swe** [acchou/html-css-cheat-sheet#1]
In stead of scrolling up and down when searching for something it would be nice to have a list of all headings placed for example in a navbar on the left side of each page (the content of navbar would change for each page). This would give a good overview of the page and easier access when searching for something.

**Comment by acchou** [comment]
Thanks for the suggestion. So far the page has no JavaScript. I'm not opposed to it but would like to keep it to a minimum, with no dependencies. Any suggestions on implementation? PR would be welcome :)
